python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.3 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/processed_ours_alpha_10_lambda_0p01 --alpha 10 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/processed_ours_alpha_10_lambda_0p1 --alpha 10 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_64/processed_ours_alpha_10_lambda_0p3 --alpha 10 --lambda_smooth 0.3 --max_iter 10

python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.3 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/processed_ours_alpha_10_lambda_0p01 --alpha 10 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/processed_ours_alpha_10_lambda_0p1 --alpha 10 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_80/processed_ours_alpha_10_lambda_0p3 --alpha 10 --lambda_smooth 0.3 --max_iter 10

python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.3 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/processed_ours_alpha_10_lambda_0p01 --alpha 10 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/processed_ours_alpha_10_lambda_0p1 --alpha 10 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_96/processed_ours_alpha_10_lambda_0p3 --alpha 10 --lambda_smooth 0.3 --max_iter 10

python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.3 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/processed_ours_alpha_10_lambda_0p01 --alpha 10 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/processed_ours_alpha_10_lambda_0p1 --alpha 10 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_112/processed_ours_alpha_10_lambda_0p3 --alpha 10 --lambda_smooth 0.3 --max_iter 10

python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/processed_ours_alpha_100_lambda_0p1 --alpha 100 --lambda_smooth 0.3 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/processed_ours_alpha_10_lambda_0p01 --alpha 10 --lambda_smooth 0.01 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/processed_ours_alpha_10_lambda_0p1 --alpha 10 --lambda_smooth 0.1 --max_iter 10
python -m scripts.pyhysco_push_4d /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/raw/image_config.json --output_dir /home/laurin/workspace/PyHySCO/data/downsampling_analysis/fov_128/processed_ours_alpha_10_lambda_0p3 --alpha 10 --lambda_smooth 0.3 --max_iter 10
